version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_airbnb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js
      - ./import.sh:/docker-entrypoint-initdb.d/import.sh
      - ../docs:/data/docs

volumes:
  mongo_data: